# Change these first
owner: oula-health # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Oula Main Site
    url: https://oulahealth.com
  - name: Oula Patient Portal
    url: https://my.oulahealth.com
  - name: Oula API v1
    url: https://api.oulahealth.com/api/v1/ping
    expectedStatusCodes:  
    - 304
  - name: Oula API v2
    url: https://api.oulahealth.com/v2/
    expectedStatusCodes: 
    - 401
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  navbar:
    - title: Status
      href: /
    - title: Oula
      href: https://oulahealth.com
  baseUrl: /status
  logoUrl: https://my.oulahealth.com/logo192.png
  name: Oula Health
  introTitle: Current Status for Oula Health Services
  introMessage: Oula is a modern maternity center that combines the best of obstetrics and midwifery care to deliver an evidence-based and personalized pregnancy experience.
  theme: light
  favicon: https://my.oulahealth.com/favicon.ico
  themeUrl: https://oula-health.github.io/status/my-custom-theme.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
